=== SergioFiel/SEW/LaVuelta2026/xml/etapa.dtd
<!ELEMENT etapas (etapa+)>

<!ELEMENT etapa (nombre, longitud, fecha, tiempoGanador, velocidadMedia,
                  desnivel, inicio, fin, tipo, localidades, galeria,
                  videos, sonidos, lugarSalida, lugarEntrada, hitos,
                  puntosAnonimos, primerosEtapa, primerosGeneral,
                  primerosEquipos)>
<!ATTLIST etapa numero CDATA #REQUIRED>

<!-- Datos generales de la etapa -->
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT tiempoGanador (#PCDATA)>
<!ELEMENT velocidadMedia (#PCDATA)>
<!ELEMENT desnivel (#PCDATA)>
<!ELEMENT inicio (#PCDATA)>
<!ELEMENT fin (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>

<!-- Referencias/bibliografía: mínimo 3 -->
<!ELEMENT localidades (localidad, localidad, localidad, localidad*)>
<!ELEMENT localidad (#PCDATA)>
<!ATTLIST localidad nombre CDATA #REQUIRED>

<!-- Galería de fotos: mínimo 1, máximo 5 -->
<!ELEMENT galeria (fotografia, fotografia?, fotografia?, fotografia?, fotografia?)>
<!ELEMENT fotografia (#PCDATA)>

<!-- Galería de vídeos: mínimo 1, máximo 3 -->
<!ELEMENT videos (video, video?, video?)>
<!ELEMENT video (#PCDATA)>

<!-- Galería de podcasts: mínimo 1, máximo 3 -->
<!ELEMENT sonidos (sonido, sonido?, sonido?)>
<!ELEMENT sonido (#PCDATA)>

<!-- Coordenadas de salida y llegada -->
<!ELEMENT lugarSalida (longitud, latitud, altitud)>
<!ELEMENT lugarEntrada (longitud, latitud, altitud)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>

<!-- Hitos: puertos de montaña, sprint intermedio, sprint bonificado -->
<!ELEMENT hitos (puertosMontana, sprintIntermedio, sprintBonificado)>

<!ELEMENT puertosMontana (puertoMontana+)>
<!ELEMENT puertoMontana (longitud, latitud, altitud, distancia)>
<!ATTLIST puertoMontana categoria CDATA #REQUIRED>

<!ELEMENT sprintIntermedio (longitud, latitud, altitud, distancia)>
<!ELEMENT sprintBonificado (longitud, latitud, altitud, distancia)>
<!ELEMENT distancia (#PCDATA)>

<!-- Puntos anónimos: número variable de puntos -->
<!ELEMENT puntosAnonimos (puntoAnonimo+)>
<!ELEMENT puntoAnonimo (longitud, latitud, altitud, distancia)>

<!-- Clasificaciones -->
<!ELEMENT primerosEtapa (primero, segundo, tercero)>
<!ELEMENT primerosGeneral (primero, segundo, tercero)>
<!ELEMENT primerosEquipos (primero, segundo, tercero)>

<!ELEMENT primero EMPTY>
<!ATTLIST primero nombre CDATA #REQUIRED>

<!ELEMENT segundo (diferenciaTiempo)>
<!ATTLIST segundo nombre CDATA #REQUIRED>

<!ELEMENT tercero (diferenciaTiempo)>
<!ATTLIST tercero nombre CDATA #REQUIRED>

<!ELEMENT diferenciaTiempo (#PCDATA)>

=== SergioFiel/SEW/LaVuelta2026/xml/etapa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE etapas SYSTEM "etapa.dtd">
<etapas>
    <etapa numero="12">
        <nombre>Vera a Calar Alto</nombre>
        <longitud>166.6</longitud>
        <fecha>Jueves, 3 de septiembre</fecha>
        <tiempoGanador>4h 29' 53''</tiempoGanador>
        <velocidadMedia>37,04 kmh</velocidadMedia>
        <desnivel>4568 m</desnivel>
        <inicio>Vera</inicio>
        <fin>Calar Alto</fin>
        <tipo>Montaña</tipo>
        <localidades>
            <localidad nombre ="Vera">https://es.wikipedia.org/wiki/Vera_(Almer%C3%ADa)</localidad>
            <localidad nombre ="Albanchez">https://es.wikipedia.org/wiki/Alb%C3%A1nchez</localidad>
            <localidad nombre ="Almanzora">https://es.wikipedia.org/wiki/Almanzora</localidad>
            <localidad nombre ="Cobdar">https://es.wikipedia.org/wiki/C%C3%B3bdar</localidad>
            <localidad nombre ="Chercos">https://es.wikipedia.org/wiki/Chercos</localidad>
            <localidad nombre ="Velefique">https://es.wikipedia.org/wiki/Velefique</localidad>
            <localidad nombre ="Bacares">https://es.wikipedia.org/wiki/Bacares</localidad>
        </localidades>
        <galeria>
            <fotografia>../multimedia/Bacares.jpg</fotografia>
            <fotografia>../multimedia/Vera1.jpg</fotografia>
            <fotografia>../multimedia/Vera2.jpg</fotografia>
        </galeria>
        <videos>
            <video>p</video>
        </videos>
        <sonidos>
            <sonido>p</sonido>
        </sonidos>
        <lugarSalida>
            <longitud>p</longitud>
            <latitud>p</latitud>
            <altitud>p</altitud>
        </lugarSalida>
        <lugarEntrada>
            <longitud>p</longitud>
            <latitud>p</latitud>
            <altitud>p</altitud>
        </lugarEntrada>
        <hitos>
            <puertosMontana>
                <puertoMontana categoria="">
                <longitud>p</longitud>
                <latitud>p</latitud>
                <altitud>p</altitud>
                <distancia >p</distancia>
                </puertoMontana>
            </puertosMontana>
            <sprintIntermedio>
                <longitud></longitud>
                <latitud></latitud>
                <altitud></altitud>
                <distancia ></distancia>
            </sprintIntermedio>
            <sprintBonificado>
                <longitud></longitud>
                <latitud></latitud>
                <altitud></altitud>
                <distancia ></distancia>
            </sprintBonificado>
        </hitos>
        <puntosAnonimos>
            <puntoAnonimo>
                <longitud>-1.8933</longitud>
                <latitud>37.2424</latitud>
                <altitud>293</altitud>
                <distancia>8</distancia>
            </puntoAnonimo>
            <puntoAnonimo>
                <longitud>-1.9483</longitud>
                <latitud>37.2399</latitud>
                <altitud>500</altitud>
                <distancia>22</distancia>
            </puntoAnonimo>
            <puntoAnonimo>
                <longitud>-1.9994</longitud>
                <latitud>37.2375</latitud>
                <altitud>561</altitud>
                <distancia>35</distancia>
            </puntoAnonimo>
            <puntoAnonimo>
                <longitud>-2.0584</longitud>
                <latitud>37.2347</latitud>
                <altitud>632</altitud>
                <distancia>50</distancia>
            </puntoAnonimo>
            <puntoAnonimo>
                <longitud>-2.1174</longitud>
                <latitud>37.2320</latitud>
                <altitud>816</altitud>
                <distancia>65</distancia>
            </puntoAnonimo>
            <puntoAnonimo>
                <longitud>-2.1764</longitud>
                <latitud>37.2292</latitud>
                <altitud>1112</altitud>
                <distancia>80</distancia>
            </puntoAnonimo>
            <puntoAnonimo>
                <longitud>-2.2550</longitud>
                <latitud>37.2255</latitud>
                <altitud>1133</altitud>
                <distancia>100</distancia>
            </puntoAnonimo>
            <puntoAnonimo>
                <longitud>-2.3140</longitud>
                <latitud>37.2228</latitud>
                <altitud>1015</altitud>
                <distancia>115</distancia>
            </puntoAnonimo>
            <puntoAnonimo>
                <longitud>-2.3730</longitud>
                <latitud>37.2200</latitud>
                <altitud>1400</altitud>
                <distancia>130</distancia>
            </puntoAnonimo>
            <puntoAnonimo>
                <longitud>-2.4516</longitud>
                <latitud>37.2164</latitud>
                <altitud>1959</altitud>
                <distancia>150</distancia>
            </puntoAnonimo>
        </puntosAnonimos>
        <primerosEtapa>
            <primero nombre =""></primero>
            <segundo nombre ="">
                <diferenciaTiempo></diferenciaTiempo>
            </segundo>
            <tercero nombre ="">
                <diferenciaTiempo></diferenciaTiempo>
            </tercero>

        </primerosEtapa>
        <primerosGeneral>
            <primero nombre =""></primero>
                <segundo nombre ="">
                    <diferenciaTiempo></diferenciaTiempo>
                </segundo>
                <tercero nombre ="">
                    <diferenciaTiempo></diferenciaTiempo>
                </tercero>
        </primerosGeneral>
        <primerosEquipos>
            <primero nombre =""></primero>
            <segundo nombre ="">
                <diferenciaTiempo></diferenciaTiempo>
            </segundo>
            <tercero nombre ="">
                <diferenciaTiempo></diferenciaTiempo>
            </tercero>
        </primerosEquipos>

    </etapa>
</etapas>
